#!/bin/bash -login
#PBS -j oe
#PBS -l nodes=1:ppn=1,walltime=4:00:00,mem=10gb
#PBS -m a
#PBS -r n

# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission

module load GNU/4.9
module load R/3.3.2
module load SAMTools/1.2
module load pandoc/1.17.3

cd ${PBS_O_WORKDIR} || exit #Go to directory with sequencing files

for alignrun in `ls -d *[BG][TS]`
  do
    for bamfile in `ls ${alignrun}/*sorted.bam`
      do samtools flagstat ${bamfile}
    done > ${alignrun}/stats.txt
done

for transcriptrun in `ls -d [BR][OR]*/`
do cd ${transcriptrun} || exit
R --file=../zealous-octo-tanuki/2.1_Reformat_TranscriptCounts.R
cd - || exit
done


cd zealous-octo-tanuki/ || exit

R --file=2.2_RunHTSeqAnalysis.R

R --file=2.4_MappingRates.R

#R --file=2.5_DifferentialGenesPseudoR.R

#R --file=2.6_MitsuiAnnotate.R

R --file=RunTopGo.R
