#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=1,walltime=4:00:00,mem=10gb
#PBS -m a
#PBS -r n

# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission

cd ${PBS_O_WORKDIR} || exit #Go to directory with sequencing files

for alignrun in `ls -d *[BG][TS]/`
do
for bamfile in `ls ${alignrun}*sorted.bam`
do samtools stats ${bamfile} 
done > ${alignrun}stats.txt
done

module load pandoc
cd zealous-octo-tanuki/

R --file=RunHTSeqAnalysis.R

R --file=MappingRates.R

R --file=DifferentialGenesPseudoR.R