#!/bin/sh -login
#PBS -j oe
#PBS -l nodes=1:ppn=1,walltime=0:00:60,mem=10gb
#PBS -m abe

# -o : tells it where to put output from your job
# -j oe : specifies that output and error messages from your job can be placed in the same location
# -l : resource requests (maximum amounts needed for each)
# -M : email address to send status updates to
# -m abe : what to send email updates about (abort, begin, end)
# -N : names your job
# -r n : tells it not to re-run the script in the case of an error (so it doesn't overwrite any results generated$
# -t 0-? : job numbers for array submission


module load SAMTools/1.2

cd ${PBS_O_WORKDIR}

samtools view -q 30 -b -T ${genome} ${bsname}.sam > ${bsname}.bam

samtools sort ${bsname}.bam ${bsname}.sorted

samtools index ${bsname}.sorted.bam

qsub ../scripts/htseq.qsub -N ${bsname}.HTseq -v genome=$[genome},index=${index},gff=${gff},bsname=${bsname},indiv=${indiv}