RNAData_dir=/Volumes/radishGenomics/AssembledSequencingFiles/AE_RNA_Assembly
RapGenomeData_dir=/Volumes/radishGenomics/AssembledSequencingFiles/MoghePublished
SatGenomeData_dir=/Volumes/radishGenomics/PublicData/RsativusGenome
GSNAP_dir=/usr/local
kmer=15