---
title: "TopGo"
author: "Amanda Charbonneau"
date: '`r Sys.Date()`'
output:
  html_document:
    code_folding: hide
    collapsed: no
    df_print: paged
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 5
    toc_float: yes
  html_notebook:
    toc: yes
    toc_depth: 5
---




```{r setup, include=FALSE}
bioconductors <- function(x){
    x<- as.character(match.call()[[2]])
    if (!require(x, character.only = TRUE)){
      source("https://bioconductor.org/biocLite.R")
      biocLite(pkgs=x)
      require(x, character.only = TRUE)
    }
}

packages<-function(x){
  x<-as.character(match.call()[[2]])
  if (!require(x,character.only=TRUE)){
    install.packages(pkgs=x,repos="http://cran.r-project.org")
    require(x,character.only=TRUE)
  }
}


bioconductors(topGO)
bioconductors(Rgraphviz)

packages(DT)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

```

```{r, eval=FALSE}
# This script is automatically run by RunTopGo.R
# To run manually or test, you need to run this box. Change the genome as desired

genome <- "Mitsui2015"

```

```{r}

mitsuiGO <- readMappings(file ="../Genomes/MitsuiAnnotation.map")

```



### GO analysis

```{r, include=FALSE}
# read in files

allgeneList <- read.table(paste("../DEseqOutput/", genome,"_GS_background_AsMitsui.names.uniq", sep=""), sep=",")

## HvL

hvlgeneList <- read.table(paste( "../DEseqOutput/", genome,"_GS_deseq2_FC0_HvL_AsMitsui.names.uniq", sep = ""))


hvlgenes <- as.vector(as.matrix(hvlgeneList))

ifelse(genome == "Mitsui2015", 
       allgenes <- as.vector(as.matrix(allgeneList$V1)),
       allgenes <- as.vector(as.matrix(allgeneList$V2)))

hvlallList <- factor(as.integer( allgenes %in% hvlgenes))
names(hvlallList) <- allgenes

##KvR

kvrgeneList <- read.table(paste( "../DEseqOutput/", genome,"_GS_deseq2_FC0_KvR_AsMitsui.names.uniq", sep = ""))

kvrgenes <- as.vector(as.matrix(kvrgeneList))

ifelse(genome == "Mitsui2015", 
       allgenes <- as.vector(as.matrix(allgeneList$V1)),
       allgenes <- as.vector(as.matrix(allgeneList$V2)))

kvrallList <- factor(as.integer( allgenes %in% kvrgenes))
names(kvrallList) <- allgenes


```

## High vs Low

```{r}
HvLGOdata <- new("topGOdata", ontology = "BP", allGenes = hvlallList,
            annot = annFUN.gene2GO, gene2GO = mitsuiGO)

HvLGOdata
```

```{r}
test.stat <- new("classicCount", testStatistic = GOFisherTest, name = "Fisher test")

```


```{r}
resultFisher <- getSigGroups(HvLGOdata, test.stat)

resultFisher
```

```{r}
pvalFis <- score(resultFisher)
hist(pvalFis, 50, xlab = "p-values")

```


```{r, Top5GoHvL}
printGraph(HvLGOdata, resultFisher, firstSigNodes = 5, fn.prefix = genome, useInfo = "all", pdfSW = TRUE)

```

```{r}
allRes <- GenTable(HvLGOdata, classic = resultFisher, topNodes=1000,
                 orderBy = "classic", ranksOf = "classic")
                 

write.csv(allRes, paste("../DEseqOutput/", genome, "Go_HvL.csv", sep=""))

DT::datatable(allRes)

```

## KBS vs Reed

```{r}
KvRGOdata <- new("topGOdata", ontology = "BP", allGenes = kvrallList,
            annot = annFUN.gene2GO, gene2GO = mitsuiGO)

KvRGOdata
```


```{r}
resultFisher <- getSigGroups(KvRGOdata, test.stat)

resultFisher
```

```{r}
pvalFis <- score(resultFisher)
hist(pvalFis, 50, xlab = "p-values")

```


```{r, Top5GoKvR}
printGraph(KvRGOdata, resultFisher, firstSigNodes = 5, fn.prefix = genome, useInfo = "all", pdfSW = TRUE)

```

```{r}
allRes <- GenTable(KvRGOdata, classic = resultFisher, topNodes=1000,
                 orderBy = "classic", ranksOf = "classic")
                 

write.csv(allRes, paste("../DEseqOutput/", genome, "Go_KvR.csv", sep=""))

DT::datatable(allRes)

```